// <auto-generated />
using System;
using ConsoleWinTasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleWinTasks.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20241020123734_BranchAndCountryOfStudio")]
    partial class BranchAndCountryOfStudio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleWinTasks.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CopiesSold")
                        .HasColumnType("int");

                    b.Property<string>("GameMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.Property<string>("StuleGame")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Game__3214EC073EE53829");

                    b.HasIndex("StudioId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("ConsoleWinTasks.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Studio");

                    b.ToTable("Studio", (string)null);
                });

            modelBuilder.Entity("ConsoleWinTasks.StudioBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_StudioBranch");

                    b.HasIndex("StudioId");

                    b.ToTable("StudioBranch", (string)null);
                });

            modelBuilder.Entity("ConsoleWinTasks.StudioCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_StudioCountry");

                    b.HasIndex("StudioId");

                    b.ToTable("StudioCountry", (string)null);
                });

            modelBuilder.Entity("ConsoleWinTasks.Game", b =>
                {
                    b.HasOne("ConsoleWinTasks.Studio", "Studio")
                        .WithMany("Games")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Game_Studio");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("ConsoleWinTasks.StudioBranch", b =>
                {
                    b.HasOne("ConsoleWinTasks.Studio", "Studio")
                        .WithMany("StudioBranches")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("ConsoleWinTasks.StudioCountry", b =>
                {
                    b.HasOne("ConsoleWinTasks.Studio", "Studio")
                        .WithMany("StudioCountries")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("ConsoleWinTasks.Studio", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("StudioBranches");

                    b.Navigation("StudioCountries");
                });
#pragma warning restore 612, 618
        }
    }
}
